# Replace old effect names with new standardized names


# A dictionary with old names as keys, and new names as values
replacements = {
    "Heal Health": "Health Restoration",
    "Restore Health": "Health Restoration",
    "Damage Health": "Health Damage",
    "Ravage Health": "Health Damage",
    "Drain Health": "Health Damage",
    "Lingering Health": "Lingering Health Restoration",
    "Gradual Ravage Health": "Lingering Health Damage",
    "Lingering Damage Health": "Lingering Health Damage",
    "Fortify Health": "Increased Health",
    "Increase Max Health": "Increased Health",
    "Increases health": "Increased Health",
    "Increase Health Recovery": "Vitality Increase",
    "Vitality": "Vitality Increase",
    "Regenerate Health": "Vitality Increase",
    "Damage Health Regeneration": "Vitality Decrease",
    "Defile": "Vitality Decrease",
    "Restore Magicka": "Magicka Restoration",
    "Damage Magicka": "Magicka Damage",
    "Ravage Magicka": "Magicka Damage",
    "Drain Magicka": "Magicka Damage",
    "Lingering Damage Magicka": "Lingering Magicka Damage",
    "Fortify Magicka": "Increased Magicka",
    "Fortify Maximum Magicka": "Increased Magicka",
    "Increase Max Magicka": "Increased Magicka",
    "Increase Maximum Magicka": "Increased Magicka",
    "Magicka Recovery": "Focus Increase",
    "Increase Magicka Recovery": "Focus Increase",
    "Regenerate Magicka": "Focus Increase",
    "Damage Magicka Regen": "Focus Decrease",
    "Damage Magicka Regeneration": "Focus Decrease",
    "Heal Stamina": "Stamina Restoration",
    "Restore Stamina": "Stamina Restoration",
    "Damage Stamina": "Stamina Damage",
    "Ravage Stamina": "Stamina Damage",
    "Lingering Damage Stamina": "Lingering Stamina Damage",
    "Fortify Stamina": "Increased Stamina",
    "Increase Max Stamina": "Increased Stamina",
    "Increase Maximum Stamina": "Increased Stamina",
    "Restore Fatigue": "Fatigue Restoration",
    "Damage Stamina Regen": "Fatigue Increase",
    "Damage Stamina Regeneration": "Fatigue Increase",
    "Damage Fatigue": "Fatigue Increase",
    "Drain Fatigue": "Fatigue Increase",
    "Increase Stamina Recovery": "Fatigue Decrease",
    "Regenerate Stamina": "Fatigue Decrease",
    "Fortify Fatigue": "Fatigue Capacity",
    "Restore Agility": "Agility Restoration",
    "Fortify Agility": "Agility Increase",
    "Increase Agility": "Agility Increase",
    "Increased Agility": "Agility Increase",
    "Weapon Critical": "Agility Increase",
    "Increase Lethal Strike": "Agility Increase",
    "Fortify Acrobatics": "Agility Increase",
    "Increased Jumping": "Agility Increase",
    "Increase Jumping": "Agility Increase",
    "Jumping": "Agility Increase",
    "Fortify Attack": "Agility Increase",
    "Reflect Damage": "Agility Increase",
    "Fortify Light Armor": "Agility Increase",
    "Improve Climbing": "Agility Increase",
    "Increase disarm": "Agility Increase",
    "Increase lock picking and disarm": "Agility Increase",
    "Increase lock picking": "Agility Increase",
    "Fortify Pickpocket": "Agility Increase",
    "Fortify Lockpicking": "Agility Increase",
    "Fortify Sneak": "Agility Increase",
    "Damage Agility": "Agility Decrease",
    "Damagge Agility": "Agility Decrease",
    "Drain Agility": "Agility Decrease",
    "Enervation": "Agility Decrease",
    "Restore Endurance": "Endurance Restoration",
    "Fortify Endurance": "Endurance Increase",
    "Fortify Endurnace": "Endurance Increase",
    "Increase Endurance": "Endurance Increase",
    "Immunity to all special attacks": "Endurance Increase",
    "Increase Armor": "Endurance Increase",
    "Increase Armory": "Endurance Increase",
    "Increase Armor Value": "Endurance Increase",
    "Fortify Armor": "Endurance Increase",
    "Ironskin": "Endurance Increase",
    "Shield": "Endurance Increase",
    "Protection": "Endurance Increase",
    "Increase Defense": "Endurance Increase",
    "Fortify Defense": "Endurance Increase",
    "Damage Endurance": "Endurance Decrease",
    "Drain Endurance": "Endurance Decrease",
    "Vulnerability": "Endurance Decrease",
    "Fracture": "Endurance Decrease",
    "Restore Intelligence": "Intelligence Restoration",
    "Add Intelligence": "Intelligence Increase",
    "Fortify Intelligence": "Intelligence Increase",
    "Increase Intelligence": "Intelligence Increase",
    "Dispel Magic": "Intelligence Increase",
    "Dispell Magic": "Intelligence Increase",
    "Dispel": "Intelligence Increase",
    "Increase Precise Magic": "Intelligence Increase",
    "Spell Critical": "Willpower Increase",
    "Increase Spell Power": "Intelligence Increase",
    "Detect Magic": "Intelligence Increase",
    "Detect Enchantment": "Intelligence Increase",
    "Damage Intelligence": "Intelligence Decrease",
    "Drain Intelligence": "Intelligence Decrease",
    "Damage Spell Points": "Intelligence Decrease",
    "Restore Personality": "Personality Restoration",
    "Fortify Personality": "Personality Increase",
    "Increase Personality": "Personality Increase",
    "Fortify Persuasion": "Personality Increase",
    "Fortify Barter": "Personality Increase",
    "Damage Personality": "Personality Decrease",
    "Drain Personality": "Personality Decrease",
    "Restore Speed": "Speed Restoration",
    "Fortify Speed": "Speed Increase",
    "Increase Speed": "Speed Increase",
    "Speed": "Speed Increase",
    "Damage Speed": "Speed Decrease",
    "Drain Speed": "Speed Decrease",
    "Hindrance": "Speed Decrease",
    "Slow": "Speed Decrease",
    "Restore Strength": "Strength Restoration",
    "Fortify Strength": "Strength Increase",
    "Increase Strength": "Strength Increase",
    "Increased Strength": "Strength Increase",
    "Increase Weapon Power": "Strength Increase",
    "Increase Attack": "Strength Increase",
    "Increase Attack Damage": "Strength Increase",
    "Increase Damage": "Strength Increase",
    "Fortify Heavy Armor": "Strength Increase",
    "Fortify Two-handed": "Strength Increase",
    "Fortify One-handed": "Strength Increase",
    "Fortify Block": "Strength Increase",
    "Fortify Smithing": "Strength Increase",
    "Fortify Carry Weight": "Strength Increase",
    "Feather": "Strength Increase",
    "Casts Mystic Might": "Strength Increase",
    "Damage Strength": "Strength Decrease",
    "Drain Strength": "Strength Decrease",
    "Burden": "Strength Decrease",
    "Maim": "Strength Decrease",
    "Restore Willpower": "Willpower Restoration",
    "Fortify Willpower": "Willpower Increase",
    "Increase Willpower": "Willpower Increase",
    "Increase Will": "Willpower Increase",
    "Reflect": "Willpower Increase",
    "Reflect Spell": "Willpower Increase",
    "Spell Reflection": "Willpower Increase",
    "Increase Magic Resistance": "Willpower Increase",
    "Resist Magic": "Willpower Increase",
    "Resist Magicka": "Willpower Increase",
    "Increase Spell Resist": "Willpower Increase",
    "Spell Resistance": "Willpower Increase",
    "Spell Absorption": "Willpower Increase",
    "Damage Willpower": "Willpower Decrease",
    "Drain Willpower": "Willpower Decrease",
    "Weakness to Magic": "Willpower Decrease",
    "Breach": "Willpower Decrease",
    "Uncertainty": "Willpower Decrease",
    "Resist Disease": "Disease Resistance",
    "Resist Common Disease": "Disease Resistance",
    "Cure Disease": "Disease Cure",
    "Cure Common Disease": "Disease Cure",
    "Cure Blight Disease": "Blight Disease Cure",
    "Felldew Effect": "Felldew Effect",
    "Resist Poison": "Poison Resistance",
    "Weakness to Poison": "Poison Vulnerability",
    "Deadly Poison": "Poison",
    "Lethal Poison": "Poison",
    "Poison": "Poison",
    "Cure Poison": "Poison Cure",
    "Entrapment": "Paralysis",
    "Paralysis": "Paralysis",
    "Paralyze": "Paralysis",
    "Cure Paralysis": "Paralysis Cure",
    "Cure Paralyzation": "Paralysis Cure",
    "Free Action": "Paralysis Cure",
    "Resist Paralysis": "Paralysis Resistance",
    "Unstoppable": "Paralysis Resistance",
    "Increase Perception": "Perception Increase",
    "Detection": "Perception Increase",
    "Detect Treasure": "Perception Increase",
    "Detect Life": "Perception Increase",
    "Detect Key": "Perception Increase",
    "Detect Enemy": "Perception Increase",
    "Detect Animal": "Perception Increase",
    "Fortify Marksman": "Perception Increase",
    "Heroism": "Heroism",
    "Fear": "Fear",
    "Timidity": "Fear",
    "Cowardice": "Fear",
    "Frenzy": "Frenzy",
    "Diminution": "Diminution",
    "Dimunition": "Diminution",
    "Invisible": "Invisibility",
    "Invisibility": "Invisibility",
    "Chameleon": "Chameleon",
    "Resist Fire": "Fire Resistance",
    "Fire Shield": "Fire Resistance",
    "Weakness to Fire": "Fire Vulnerability",
    "Fire Damage": "Fire Spells Enhancement",
    "Resist Frost": "Frost Resistance",
    "Resist Cold": "Frost Resistance",
    "Frost Shield": "Frost Resistance",
    "Weakness to Frost": "Frost Vulnerability",
    "Frost Damage": "Frost Spells Enhancement",
    "Resist Shock": "Shock Resistance",
    "Shock Shield": "Shock Resistance",
    "Lightning Shield": "Shock Resistance",
    "Weakness to Shock": "Shock Vulnerability",
    "Shock Damage": "Shock Spells Power",
    "Fortify Alteration": "Alteration Spells Enhancement",
    "Drain Alteration": "Alteration Spells Weakening",
    "Fortify Conjuration": "Conjuration Spells Enhancement",
    "Fortify Destruction": "Destruction Spells Enhancement",
    "Fortify Illusion": "Illusion Spells Enhancement",
    "Fortify Restoration": "Restoration Spells Enhancement",
    "Fortify Enchanting": "Enchanting Enhancement",
    "Restore Luck": "Luck Restoration",
    "Damage Luck": "Luck Damage",
    "Drain Luck": "Luck Damage",
    "Increase Luck": "Luck Increase",
    "Fortify Luck": "Luck Increase",
    "Night-Eye": "Night Vision",
    "Night Eye": "Night Vision",
    "Light": "Light",
    "Blind": "Blindness",
    "Silence": "Silence",
    "Waterbreathing": "Water Breathing",
    "Water Breathing": "Water Breathing",
    "Water Walking": "Water Walking",
    "Swift Swim": "Swimming Speed",
    "Improve Jumping": "Improved Jumping",
    "Telekinesis": "Telekinesis",
    "Recall": "Teleportation",
    "Etherealness": "Etherealness",
    "Slowfall": "Slow Fall",
    "Levitate": "Levitation",
    "Increase Potency": "Potency Increase",
    "Charm Mortal": "Charming a Mortal",
    "Tongues": "Polyglotism",
    "Death": "Death",
    "Vampirism": "Vampirism",
    "Lycanthropy": "Lycanthropy",
}


with open("data/01_parsed.txt", "r") as fname:
    with open("data/02_renamed.txt", "w") as file:
        for line in fname:
            line = line.strip()
            if line in replacements:
                line = "\t" + replacements[line]  # Preserve indentation of the replaced effect names
            file.write(line + "\n")
